version: "3"
x-app: &base-app
  build:
    context: .
    target: app
  env_file: 
    - ./.app.env

services:
  app:
    <<: *base-app
    build:
      context: .
      target: app
      args:
        - BUILD_DATE
        - BUILD_REVISION
        - BUILD_VERSION
    # @TODO update image to location of official image for app deployments 
    image: djangotemplate-app
    command: /app/deploy/app/docker-run.sh

  dev:
    <<: *base-app
    build:
      context: .
      target: dev
    depends_on:
      mssql:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app/src
    ports:
      - "8000:8000"

  test:
    <<: *base-app
    build:
      context: .
      target: test
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      PYTEST_ADDOPTS:

  mssql:
    build:
      context: .
      target: mssql
    ports:
     - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql
    env_file:
      - ./.mssql.env
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -U $$SA_USER -P $$SA_PASSWORD -d example_database -Q "SELECT 1"
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  mssql: