x-app: &base-app
  build:
    context: .
    target: app
  env_file: 
    - ./.app.env

services:
  app:
    <<: *base-app
    build:
      context: .
      target: app
    image: ${REGISTRY:-127.0.0.1:5001}/${REPOSITORY:-opdrachten/fb-locatielijst}:${VERSION:-latest}
    command: /app/deploy/docker-run.sh
    ports:
      - "8000:8000"

  dev:
    <<: *base-app
    build:
      context: .
      target: dev
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.app.env
    volumes:
      - ./:/app/src
    ports:
      - "8000:8000"

  test:
    <<: *base-app
    build:
      context: .
      target: test
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    build:
      context: .
      target: postgres
    ports:
      - 5432:5432
    volumes:
      - postgresqldata:/data/db
    env_file:
      - ./.postgres.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 10  
volumes:
  postgresqldata: