# Generated by Django 4.2.7 on 2023-11-21 10:48

from django.db import migrations, models
import django.db.models.deletion
import locations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Externe API')),
            ],
            options={
                'verbose_name': 'Externe koppeling',
                'verbose_name_plural': 'Externe koppelingen',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_code', models.IntegerField(default=locations.models.compute_building_code, verbose_name='Pandcode')),
                ('short_name', models.CharField(max_length=12, verbose_name='Afkorting')),
                ('name', models.CharField(max_length=100, verbose_name='Locatie naam')),
                ('description', models.CharField(max_length=255, verbose_name='Beschrijving')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
                ('last_modified', models.DateField(auto_now=True, verbose_name='Laatste wijziging')),
                ('street', models.CharField(max_length=100, verbose_name='Straat')),
                ('street_number', models.IntegerField(verbose_name='Straatnummer')),
                ('street_number_extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='Toevoeging')),
                ('postal_code', models.CharField(max_length=7, verbose_name='Postcode')),
                ('city', models.CharField(max_length=100, verbose_name='Plaats')),
                ('construction_year', models.IntegerField(blank=True, null=True, verbose_name='Bouwjaar')),
                ('floor_area', models.IntegerField(blank=True, null=True, verbose_name='Vloeroppervlak')),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('rd_x', models.FloatField(blank=True, null=True)),
                ('rd_y', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Notitie')),
            ],
            options={
                'verbose_name': 'Locatie',
            },
        ),
        migrations.CreateModel(
            name='LocationProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Volgorde')),
                ('label', models.CharField(max_length=100)),
                ('required', models.BooleanField(verbose_name='Verplicht veld')),
                ('multiple', models.BooleanField(verbose_name='Meervoudige invoer')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Locatie data')),
                ('property_type', models.CharField(max_length=50, verbose_name='Gegevens type')),
            ],
            options={
                'verbose_name': 'Locatie eigenschap',
                'verbose_name_plural': 'Locatie eigenschappen',
            },
        ),
        migrations.CreateModel(
            name='PropertyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, verbose_name='Optie')),
                ('location_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.locationproperty')),
            ],
            options={
                'verbose_name': 'Eigenschap optielijst',
                'verbose_name_plural': 'Eigenschappen optielijsten',
            },
        ),
        migrations.CreateModel(
            name='LocationExternalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_service_entity_id', models.CharField(max_length=100, verbose_name='Externe Id')),
                ('external_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.externalservice')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
            options={
                'verbose_name': 'Locatie koppeling',
                'verbose_name_plural': 'Locatie koppeling',
            },
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Waarde')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('location_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.locationproperty')),
                ('property_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.propertyoption')),
            ],
            options={
                'verbose_name': 'Locatie gegeven',
                'verbose_name_plural': 'Locatie gegevens',
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('building_code',), name='unique_building_code'),
        ),
    ]
