# Generated by Django 4.2.7 on 2023-11-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Externe API')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_code', models.CharField(max_length=10, verbose_name='Pandcode')),
                ('name', models.CharField(max_length=100, verbose_name='Locatie naam')),
                ('description', models.CharField(max_length=255, verbose_name='Beschrijving')),
                ('active', models.BooleanField(verbose_name='Actief')),
                ('last_change', models.DateField(verbose_name='Laatste wijziging')),
                ('street', models.CharField(max_length=100, verbose_name='Straat')),
                ('street_number', models.IntegerField(verbose_name='Straatnummer')),
                ('street_number_extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='Toevoeging')),
                ('postal_code', models.CharField(max_length=7, verbose_name='Postcode')),
                ('city', models.CharField(max_length=100, verbose_name='Plaats')),
                ('construction_year', models.IntegerField(verbose_name='Bouwjaar')),
                ('floor_area', models.IntegerField(verbose_name='Vloeroppervlak')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('rd_x', models.FloatField()),
                ('rd_y', models.FloatField()),
                ('note', models.TextField(verbose_name='Notitie')),
            ],
        ),
        migrations.CreateModel(
            name='LocationProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='Volgorde')),
                ('label', models.CharField(max_length=100)),
                ('required', models.BooleanField(verbose_name='Verplicht veld')),
                ('multiple', models.BooleanField(verbose_name='Meervoudige invoer')),
                ('description', models.CharField(verbose_name='Locatie data')),
                ('property_type', models.CharField(max_length=50, verbose_name='Gegevens type')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, verbose_name='Optie')),
                ('location_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.locationproperty')),
            ],
        ),
        migrations.CreateModel(
            name='LocationExternalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_service_entity_id', models.CharField(max_length=100, verbose_name='Externe Id')),
                ('external_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.externalservice')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Waarde')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
                ('location_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.locationproperty')),
                ('property_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.propertyoption')),
            ],
        ),
    ]
