# Generated by Django 4.2.7 on 2023-11-24 13:20

from django.db import migrations, models
import locations.models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(max_length=7, validators=[locations.models.validate_postal_code], verbose_name='Postcode'),
        ),
    ]
