# Generated by Django 5.0.1 on 2024-01-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationproperty',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Zichtbaar voor gebruikers'),
        ),
    ]
