# Generated by Django 4.2.7 on 2023-11-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyoption',
            options={'verbose_name': 'Eigenschap optie', 'verbose_name_plural': 'Eigenschappen opties'},
        ),
        migrations.RemoveField(
            model_name='locationexternalservice',
            name='external_service_entity_id',
        ),
        migrations.AddField(
            model_name='location',
            name='street_number_letter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='locationexternalservice',
            name='external_location_code',
            field=models.CharField(default='none', max_length=100, verbose_name='Externe locatie code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='location',
            name='short_name',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Afkorting'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_number_extension',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Letter toevoeging'),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='location_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locationproperty'),
        ),
        migrations.AlterField(
            model_name='locationproperty',
            name='property_type',
            field=models.CharField(choices=[('BOOL', 'Boolean'), ('DATE', 'Datum'), ('INT', 'Numeriek'), ('TEXT', 'Tekst'), ('LIST', 'Lijst')], max_length=4, verbose_name='Gegevens type'),
        ),
        migrations.AlterField(
            model_name='propertyoption',
            name='location_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locationproperty'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_location_name'),
        ),
        migrations.AddConstraint(
            model_name='propertyoption',
            constraint=models.UniqueConstraint(fields=('location_property', 'option'), name='unique_property_option'),
        ),
    ]
