# Generated by Django 4.2.7 on 2023-11-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='property_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.propertyoption'),
        ),
        migrations.AlterField(
            model_name='locationproperty',
            name='multiple',
            field=models.BooleanField(default=False, verbose_name='Meervoudige invoer'),
        ),
        migrations.AlterField(
            model_name='locationproperty',
            name='property_type',
            field=models.CharField(choices=[('BOOL', 'Boolean'), ('DATE', 'Datum'), ('EMAIL', 'E-mail'), ('INT', 'Numeriek'), ('STR', 'Tekst'), ('URL', 'Url'), ('CHOICE', 'Keuzelijst')], max_length=10, verbose_name='Gegevens type'),
        ),
        migrations.AlterField(
            model_name='locationproperty',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Verplicht veld'),
        ),
    ]
