# Generated by Django 4.2.7 on 2023-11-30 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_locationdata_property_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='property_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.propertyoption'),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Waarde'),
        ),
    ]
