# Generated by Django 4.2.7 on 2023-11-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_alter_locationdata_property_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='location_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locationproperty', verbose_name='Locatie eigenschap'),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='property_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.propertyoption', verbose_name='Optie'),
        ),
        migrations.AlterField(
            model_name='locationexternalservice',
            name='external_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.externalservice', verbose_name='Externe API'),
        ),
        migrations.AlterField(
            model_name='locationexternalservice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Locatie'),
        ),
        migrations.AlterField(
            model_name='propertyoption',
            name='location_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locationproperty', verbose_name='Locatie eigenschap'),
        ),
        migrations.AddConstraint(
            model_name='locationdata',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('property_option__isnull', False), ('value__isnull', True)), models.Q(('property_option__isnull', True), ('value__isnull', False)), _connector='OR'), name='either_field_filled'),
        ),
    ]
