# Generated by Django 5.0.2 on 2024-02-14 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Aanmaakdatum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Aanmaakdatum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationexternalservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Aanmaakdatum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationexternalservice',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Laatste wijziging'),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Laatste wijziging'),
        ),
    ]
