# Generated by Django 4.2.7 on 2023-12-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_locationdata_location_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='locationdata',
            name='either_field_filled',
        ),
        migrations.AddConstraint(
            model_name='locationdata',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('property_option__isnull', False), ('value__isnull', True)), models.Q(('property_option__isnull', True), ('value__isnull', False)), _connector='OR'), name='either_field_filled', violation_error_message='Either option or value must be filled.'),
        ),
    ]
