# Generated by Django 5.0 on 2023-12-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_remove_locationdata_either_field_filled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='active',
            field=models.CharField(choices=[('Ja', 'Ja'), ('Nee', 'Nee')], default='Ja', verbose_name='Actief'),
        ),
    ]
