# Generated by Django 5.0 on 2023-12-28 11:03

import locations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_alter_location_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalservice',
            name='short_name',
            field=models.CharField(default=None, max_length=10, validators=[locations.models.validate_short_name], verbose_name='Korte naam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationproperty',
            name='short_name',
            field=models.CharField(default=None, max_length=10, validators=[locations.models.validate_short_name], verbose_name='Korte naam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationproperty',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Omschrijving'),
        ),
        migrations.AddConstraint(
            model_name='externalservice',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_service_short_name'),
        ),
        migrations.AddConstraint(
            model_name='externalservice',
            constraint=models.UniqueConstraint(fields=('short_name',), name='unique_service_name'),
        ),
        migrations.AddConstraint(
            model_name='locationproperty',
            constraint=models.UniqueConstraint(fields=('short_name',), name='unique_location_property_name'),
        ),
        migrations.AddConstraint(
            model_name='locationproperty',
            constraint=models.UniqueConstraint(fields=('label',), name='unique_location_property_label'),
        ),
    ]
