# Generated by Django 5.0.3 on 2024-03-22 14:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_propertygroup_externalservice_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Locatie'},
        ),
        migrations.AddField(
            model_name='location',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door'),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door'),
        ),
        migrations.AddField(
            model_name='locationexternalservice',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Laatst gewijzigd door'),
        ),
        migrations.AlterField(
            model_name='externalservice',
            name='order',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Volgorde'),
        ),
        migrations.AlterField(
            model_name='locationproperty',
            name='order',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Volgorde'),
        ),
        migrations.AlterField(
            model_name='propertygroup',
            name='order',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Volgorde'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Tijdstip')),
                ('target', models.CharField(max_length=100, verbose_name='Onderdeel')),
                ('message', models.CharField(max_length=1000, verbose_name='Bericht')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location', verbose_name='Locatie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Gebruiker')),
            ],
            options={
                'verbose_name': 'Locatie log',
                'verbose_name_plural': 'Locatie logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
