# Generated by Django 5.0.6 on 2024-06-07 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_alter_externalservice_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyoption',
            options={'ordering': ['option'], 'verbose_name': 'Eigenschap optie', 'verbose_name_plural': 'Eigenschappen opties'},
        ),
        migrations.AddField(
            model_name='log',
            name='instance_id',
            field=models.IntegerField(verbose_name='Id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='instance_name',
            field=models.CharField(max_length=50, verbose_name='Object'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='external_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.externalservice'),
        ),
        migrations.AlterField(
            model_name='log',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='log',
            name='location_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.locationproperty'),
        ),
        migrations.AlterField(
            model_name='log',
            name='property_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.propertyoption'),
        ),
    ]
