# Generated by Django 5.2.9 on 2026-02-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentie_tabellen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnderhoudsContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='dienstverleningskader',
            name='dvk_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
