# Generated by Django 5.2.8 on 2026-01-12 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referentie_tabellen', '0002_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name_plural': 'Contracten'},
        ),
    ]
