# Generated by Django 5.2.9 on 2026-03-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referentie_tabellen", "0003_alter_gelieerdepartij_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="persoon",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="persoon",
            name="telefoonnr",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
