# Generated by Django 5.2.8 on 2026-01-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentie_tabellen', '0003_alter_contract_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leverancier1s1p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ThemaPortefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
