# Generated by Django 5.0.2 on 2024-02-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_docs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentation",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
