# Generated by Django 5.0.1 on 2024-01-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_remove_locationdata_either_field_filled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locationexternalservice",
            name="external_location_code",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Externe locatie code"),
        ),
    ]
