# Generated by Django 5.0.3 on 2024-03-19 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0009_propertygroup_externalservice_order_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="locationdata",
            name="either_field_filled",
        ),
        migrations.RenameField(
            model_name="locationdata",
            old_name="property_option",
            new_name="_property_option",
        ),
        migrations.RenameField(
            model_name="locationdata",
            old_name="value",
            new_name="_value",
        ),
        migrations.AlterField(
            model_name="externalservice",
            name="order",
            field=models.IntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Volgorde"
            ),
        ),
        migrations.AlterField(
            model_name="locationproperty",
            name="order",
            field=models.IntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Volgorde"
            ),
        ),
        migrations.AlterField(
            model_name="propertygroup",
            name="order",
            field=models.IntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Volgorde"
            ),
        ),
        migrations.AddConstraint(
            model_name="locationdata",
            constraint=models.CheckConstraint(
                check=models.Q(("_property_option__isnull", False), ("_value__isnull", False), _negated=True),
                name="either_field_filled",
                violation_error_message="Either option or value must be filled.",
            ),
        ),
    ]
