# Generated by Django 5.0.6 on 2024-06-17 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0012_alter_propertyoption_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalservice",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="location",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="locationdata",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="locationexternalservice",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="locationproperty",
            name="last_modified_by",
        ),
        migrations.RemoveField(
            model_name="propertyoption",
            name="last_modified_by",
        ),
    ]
