# Generated by Django 5.2.8 on 2026-01-30 12:29

import django.db.models.deletion
import fblocatie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referentie_tabellen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pand_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Pand identificatie')),
                ('vot_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Verblijfsobject identificatie')),
                ('straat', models.CharField(max_length=80)),
                ('postcode', models.CharField(max_length=6)),
                ('huisnummer', models.IntegerField()),
                ('huisletter', models.CharField(blank=True, max_length=41, null=True)),
                ('huisnummertoevoeging', models.CharField(blank=True, max_length=4, null=True)),
                ('woonplaats', models.CharField(max_length=50)),
                ('rd_x', models.FloatField(blank=True, null=True, verbose_name='RD_x')),
                ('rd_y', models.FloatField(blank=True, null=True, verbose_name='RD_y')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('map_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Adressen',
            },
        ),
        migrations.CreateModel(
            name='LocatieTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aanmaakdatum')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Laatste wijziging')),
                ('nummer', models.IntegerField(blank=True, null=True, verbose_name='Locatieteam')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mailadres')),
                ('loc_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='loc_manager', to='referentie_tabellen.persoon', verbose_name='Locatiemanager')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vastgoed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GV_key', models.CharField(blank=True, null=True, verbose_name='GV(planon)')),
                ('gv_id', models.CharField(blank=True, null=True, verbose_name='BRES ID')),
                ('bouwjaar', models.IntegerField(blank=True, null=True, verbose_name='Bouwjaar')),
                ('vvo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Verhuurbaar vloeroppervlak (VVO)')),
                ('bvo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bruto vloeroppervlakte (BVO)')),
                ('energielabel', models.CharField(blank=True, max_length=5, null=True, verbose_name='Energielabel')),
                ('adres', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adres_extension', to='fblocatie.adres')),
                ('asset_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='asset_manager', to='referentie_tabellen.persoon', verbose_name='Assetmanager/contract vastgoed')),
                ('bezit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='referentie_tabellen.locatiebezit', verbose_name='Eigendom / Huur')),
                ('monument_brkpb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='monument_land', to='referentie_tabellen.monumentstatus', verbose_name='Monument status landelijk')),
                ('monument_gem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='monument_gem', to='referentie_tabellen.monumentstatus', verbose_name='Monument status Amsterdam')),
                ('pl_gv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pl_gv', to='referentie_tabellen.persoon', verbose_name='Projectleider Gemeentelijk Vastgoed')),
                ('themagv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='referentie_tabellen.themaportefeuille', verbose_name='Themaportefeuille')),
            ],
            options={
                'verbose_name_plural': 'Vastgoed',
            },
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Aanmaakdatum')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Laatste wijziging')),
                ('pandcode', models.IntegerField(default=fblocatie.models.compute_pandcode, primary_key=True, serialize=False, verbose_name='FB pandcode')),
                ('afkorting', models.CharField(max_length=15, verbose_name='Afkorting')),
                ('naam', models.CharField(max_length=100, unique=True, verbose_name='Naam')),
                ('archief', models.BooleanField(default=False, verbose_name='Archief')),
                ('archief_datum', models.DateTimeField(blank=True, null=True)),
                ('beschrijving', models.TextField(blank=True, null=True, verbose_name='Beschrijving')),
                ('bezoekadres_functie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Functie afwijkend adres')),
                ('afstoten', models.DateField(blank=True, null=True)),
                ('ambtenaar', models.BooleanField(default=False, verbose_name='Primair huisvesting ambtenaren')),
                ('dvk_nr', models.IntegerField(blank=True, null=True)),
                ('routecode', models.CharField(default='FB', max_length=15)),
                ('werkplekken', models.IntegerField(blank=True, null=True)),
                ('kantoorkast', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kantoorartikelkast')),
                ('notitie', models.TextField(blank=True, null=True)),
                ('pas_loc', models.CharField(blank=True, null=True, verbose_name='1s1p locatie')),
                ('anet_loc', models.CharField(blank=True, max_length=3, null=True, verbose_name='A-net afkorting locatie')),
                ('emobj', models.IntegerField(blank=True, null=True, verbose_name='Energiemissie object')),
                ('po', models.IntegerField(blank=True, null=True, verbose_name='P&O locatie code')),
                ('priva_gbs', models.CharField(blank=True, max_length=200, null=True, verbose_name='Locatie Priva GBS')),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='locatie_adres', to='fblocatie.adres')),
                ('beveiliging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='beveiliging', to='referentie_tabellen.persoon', verbose_name='Adviseur beveiliging')),
                ('bezoekadres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bezoek_adres', to='fblocatie.adres')),
                ('budget_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='budgethouder', to='referentie_tabellen.directie')),
                ('contact_dir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contact_directie', to='referentie_tabellen.persoon', verbose_name='Contactpersoon vanuit directies')),
                ('contracten', models.ManyToManyField(blank=True, to='referentie_tabellen.contract')),
                ('dvk_naam', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='referentie_tabellen.dienstverleningskader')),
                ('gelieerd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='referentie_tabellen.gelieerdepartij')),
                ('loc_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='loc_coordinator', to='referentie_tabellen.persoon', verbose_name='Locatiecoordinator')),
                ('locatie_soort', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='referentie_tabellen.locatiesoort')),
                ('pand_directies', models.ManyToManyField(related_name='locatie_pand_directies', to='referentie_tabellen.directie')),
                ('pas_lc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='referentie_tabellen.leverancier1s1p', verbose_name='leverancier van 1s1p')),
                ('perceel_installateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='perceel_installateur', to='referentie_tabellen.persoon', verbose_name='E&W perceel installateur')),
                ('tom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tom', to='referentie_tabellen.persoon', verbose_name='Technisch ojectmanager (TOM)')),
                ('tsc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tsc', to='referentie_tabellen.persoon', verbose_name='Technisch service coordinator (TSC)')),
                ('veiligheid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='veiligheid', to='referentie_tabellen.persoon', verbose_name='Adviseur veiligheid')),
                ('voorzieningen', models.ManyToManyField(blank=True, to='referentie_tabellen.voorziening')),
                ('locatieteam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='fblocatie.locatieteam')),
                ('vastgoed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='locatie_vastgoed', to='fblocatie.vastgoed')),
            ],
            options={
                'ordering': ['pandcode'],
            },
        ),
    ]
