# Generated by Django 5.2.8 on 2026-01-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fblocatie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locatie',
            name='vastgoed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='locatie_vastgoed', to='fblocatie.vastgoed'),
        ),
    ]
