# Generated by Django 5.2.9 on 2026-03-02 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fblocatie", "0002_remove_locatie_dvk_nr_and_more"),
        ("referentie_tabellen", "0004_persoon_email_persoon_telefoonnr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locatie",
            name="locatieteam",
            field=models.IntegerField(blank=True, null=True, verbose_name="Locatieteam"),
        ),
        migrations.AddField(
            model_name="locatie",
            name="loc_email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email_algemeen"),
        ),
        migrations.AddField(
            model_name="locatie",
            name="loc_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="loc_manager",
                to="referentie_tabellen.persoon",
                verbose_name="Locatiemanager",
            ),
        ),
        migrations.AddField(
            model_name="locatie",
            name="loc_tel",
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name="Pand_telnr"),
        ),
        migrations.DeleteModel(
            name="LocatieTeam",
        ),
    ]
