# Generated by Django 5.2.8 on 2026-01-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fblocatie', '0002_alter_locatie_vastgoed'),
        ('referentie_tabellen', '0003_alter_contract_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locatieteam',
            name='beveiliging',
        ),
        migrations.RemoveField(
            model_name='locatieteam',
            name='contact_directie',
        ),
        migrations.RemoveField(
            model_name='locatieteam',
            name='loc_coordinator',
        ),
        migrations.RemoveField(
            model_name='locatieteam',
            name='perceel_installateur',
        ),
        migrations.RemoveField(
            model_name='locatieteam',
            name='tom',
        ),
        migrations.RemoveField(
            model_name='locatieteam',
            name='tsc',
        ),
        migrations.RemoveField(
            model_name='locatieteam',
            name='veiligheid',
        ),
        migrations.AddField(
            model_name='locatie',
            name='beveiliging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='beveiliging', to='referentie_tabellen.persoon', verbose_name='Adviseur beveiliging'),
        ),
        migrations.AddField(
            model_name='locatie',
            name='contact_directie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='contact_directie', to='referentie_tabellen.persoon', verbose_name='Contactpersoon vanuit directies'),
        ),
        migrations.AddField(
            model_name='locatie',
            name='loc_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='loc_coordinator', to='referentie_tabellen.persoon', verbose_name='Locatiecoordinator'),
        ),
        migrations.AddField(
            model_name='locatie',
            name='perceel_installateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='perceel_installateur', to='referentie_tabellen.persoon', verbose_name='E&W perceel installateur'),
        ),
        migrations.AddField(
            model_name='locatie',
            name='tom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tom', to='referentie_tabellen.persoon', verbose_name='Technisch ojectmanager (TOM)'),
        ),
        migrations.AddField(
            model_name='locatie',
            name='tsc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tsc', to='referentie_tabellen.persoon', verbose_name='Technisch service coordinator (TSC)'),
        ),
        migrations.AddField(
            model_name='locatie',
            name='veiligheid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='veiligheid', to='referentie_tabellen.persoon', verbose_name='Adviseur veiligheid'),
        ),
        migrations.AlterField(
            model_name='locatie',
            name='contracten',
            field=models.ManyToManyField(blank=True, null=True, to='referentie_tabellen.contract'),
        ),
        migrations.AlterField(
            model_name='locatie',
            name='voorzieningen',
            field=models.ManyToManyField(blank=True, null=True, to='referentie_tabellen.voorziening'),
        ),
    ]
