# Generated by Django 5.2.11 on 2026-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fblocatie", "0003_alter_locatie_locatieteam_locatie_loc_email_and_more"),
        ("referentie_tabellen", "0004_persoon_email_persoon_telefoonnr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="locatie",
            name="beveiliging",
        ),
        migrations.RemoveField(
            model_name="locatie",
            name="contact_dir",
        ),
        migrations.RemoveField(
            model_name="locatie",
            name="loc_coordinator",
        ),
        migrations.RemoveField(
            model_name="locatie",
            name="loc_manager",
        ),
        migrations.RemoveField(
            model_name="locatie",
            name="tom",
        ),
        migrations.RemoveField(
            model_name="locatie",
            name="tsc",
        ),
        migrations.RemoveField(
            model_name="locatie",
            name="veiligheid",
        ),
        migrations.AddField(
            model_name="locatie",
            name="beveiliging",
            field=models.ManyToManyField(
                blank=True,
                related_name="beveiliging",
                to="referentie_tabellen.persoon",
                verbose_name="Adviseur beveiliging",
            ),
        ),
        migrations.AddField(
            model_name="locatie",
            name="contact_dir",
            field=models.ManyToManyField(
                blank=True,
                related_name="contact_directie",
                to="referentie_tabellen.persoon",
                verbose_name="Contactpersoon vanuit directies",
            ),
        ),
        migrations.AddField(
            model_name="locatie",
            name="loc_coordinator",
            field=models.ManyToManyField(
                blank=True,
                related_name="loc_coordinator",
                to="referentie_tabellen.persoon",
                verbose_name="Locatiecoordinator",
            ),
        ),
        migrations.AddField(
            model_name="locatie",
            name="loc_manager",
            field=models.ManyToManyField(
                blank=True, related_name="loc_manager", to="referentie_tabellen.persoon", verbose_name="Locatiemanager"
            ),
        ),
        migrations.AddField(
            model_name="locatie",
            name="tom",
            field=models.ManyToManyField(
                blank=True,
                related_name="tom",
                to="referentie_tabellen.persoon",
                verbose_name="Technisch ojectmanager (TOM)",
            ),
        ),
        migrations.AddField(
            model_name="locatie",
            name="tsc",
            field=models.ManyToManyField(
                blank=True,
                related_name="tsc",
                to="referentie_tabellen.persoon",
                verbose_name="Technisch service coordinator (TSC)",
            ),
        ),
        migrations.AddField(
            model_name="locatie",
            name="veiligheid",
            field=models.ManyToManyField(
                blank=True,
                related_name="veiligheid",
                to="referentie_tabellen.persoon",
                verbose_name="Adviseur veiligheid",
            ),
        ),
    ]
