# Generated by Django 5.2.8 on 2026-01-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fblocatie', '0003_remove_locatieteam_beveiliging_and_more'),
        ('referentie_tabellen', '0004_leverancier1s1p_themaportefeuille'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adres',
            name='bag_id',
        ),
        migrations.RemoveField(
            model_name='vastgoed',
            name='monumentstatus',
        ),
        migrations.AddField(
            model_name='adres',
            name='pand_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Pand identificatie'),
        ),
        migrations.AddField(
            model_name='adres',
            name='vot_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Verblijfsobject identificatie'),
        ),
        migrations.AddField(
            model_name='locatie',
            name='afstoten',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locatie',
            name='ambtenaar',
            field=models.BooleanField(default=False, verbose_name='Primair huisvesting voor ambtenaren'),
        ),
        migrations.AddField(
            model_name='locatie',
            name='bezoekadres_functie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Functie afwijkend adres'),
        ),
        migrations.AddField(
            model_name='locatie',
            name='dienstverleningskader_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locatie',
            name='pas_lc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='referentie_tabellen.leverancier1s1p', verbose_name='leverancier van 1s1p'),
        ),
        migrations.AddField(
            model_name='locatie',
            name='priva_gbs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Locatie Priva GBS'),
        ),
        migrations.AddField(
            model_name='vastgoed',
            name='gv_id',
            field=models.CharField(blank=True, null=True, verbose_name='BRES ID'),
        ),
        migrations.AddField(
            model_name='vastgoed',
            name='monument_brkpb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='monument_land', to='referentie_tabellen.monumentstatus', verbose_name='Monument status landelijk'),
        ),
        migrations.AddField(
            model_name='vastgoed',
            name='monument_gem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='monument_gem', to='referentie_tabellen.monumentstatus', verbose_name='Monument status Amsterdam'),
        ),
        migrations.AddField(
            model_name='vastgoed',
            name='themagv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='referentie_tabellen.themaportefeuille', verbose_name='Themaportefeuille'),
        ),
        migrations.AlterField(
            model_name='locatie',
            name='anet_loc',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='A-net afkorting locatie'),
        ),
        migrations.AlterField(
            model_name='locatie',
            name='contracten',
            field=models.ManyToManyField(blank=True, to='referentie_tabellen.contract'),
        ),
        migrations.AlterField(
            model_name='locatie',
            name='voorzieningen',
            field=models.ManyToManyField(blank=True, to='referentie_tabellen.voorziening'),
        ),
    ]
